### ISSUE TITLE
feat: hover effect on "Book Your Time Now" and "Submit" button

### ISSUE THREAD

**Issue by superiorsd10** [MitAbhay/hinna-henna#20]
The `Book Your Time Now` and `Submit` button looks simple, and the hovering effect will look great here! I would like to work on this. So please assign it to me.

![SCR-20221001-na3](https://user-images.githubusercontent.com/92971894/193407140-39f05b8a-97d9-42b8-8c0d-3204f63d3122.png)
![SCR-20221001-na9](https://user-images.githubusercontent.com/92971894/193407144-c1db2765-9bae-4b5e-a7c0-3cd51b1edf85.png)

**Comment by shivam7242** [comment]
can I work on this
issue @superiorsd10

**Comment by shivam7242** [comment]
can I work on this issue ??

**Comment by MitAbhay** [comment]
@superiorsd10  Go ahead !!

**Comment by MitAbhay** [comment]
> can I work on this issue ??

You can check another issue.
