### ISSUE TITLE
Adding dynamic data to Footer

### ISSUE THREAD

**Issue by piyush-panpaliya** [MitAbhay/hinna-henna#21]
Right now the data in footer is dummy and if it is to be changed it has to be edited in code directly. Instead of this it can be done through a json file.

**Comment by piyush-panpaliya** [comment]
@MitAbhay also can this be tagged with hacktoberfest and also assigned to me

**Comment by piyush-panpaliya** [comment]
I see that theres already a issue(#7) related to footer so should I go ahead with this?

**Comment by MitAbhay** [comment]
No need for JSON files, we are thinking of a database for the repo.

**Comment by piyush-panpaliya** [comment]
okay
