### ISSUE TITLE
navbar modification

### ISSUE THREAD

**Issue by Saurav-Singh-Rauthan** [MitAbhay/hinna-henna#26]
![image](https://user-images.githubusercontent.com/54982868/193438285-9b69586b-d58e-4fa9-abe7-e1f8f162ea34.png)
<br>
navbar doesn't close after clicking the hamburger icon again   <br>
I'm thinking of creating such navbar (one in images below)   <br>
![image](https://user-images.githubusercontent.com/54982868/193438317-62b5ddb4-0719-4ee9-a401-e80279a2493e.png)
mobile/tab view : ![image](https://user-images.githubusercontent.com/54982868/193438329-2d66b6e0-1fc7-449f-84b9-bc9ee5c04c5d.png)

**Comment by MitAbhay** [comment]
Go Ahead !!

**Comment by MitAbhay** [comment]
#19  Take care of this also.

**Comment by Saurav-Singh-Rauthan** [comment]
> #19 Take care of this also.

ok
