### ISSUE TITLE
Create Contact Page

### ISSUE THREAD

**Issue by MitAbhay** [MitAbhay/hinna-henna#3]
Use the dummy contact data for this.

**Comment by Ilikepizza2** [comment]
Hello can I be assigned?

**Comment by MitAbhay** [comment]
Sure, you can work on this issue.

**Comment by kiritocode1** [comment]
### heyy :) assign me this pwease @MitAbhay

**Comment by MitAbhay** [comment]
> ### heyy :) assign me this pwease @MitAbhay

Already assigned, you can look into another issue, or can create a valuable issue by yourself.

**Comment by Ilikepizza2** [comment]
Hello there! 
Any idea why this issue is still open and I am assigned?
Afaik this issue is fixed?

**Comment by MitAbhay** [comment]
yes it is fixed.
