### ISSUE TITLE
subpages of gallery page

### ISSUE THREAD

**Issue by MitAbhay** [MitAbhay/hinna-henna#38]
- only a fixed number of images should be there on the current page
- add next page and previous page buttons.
- on clicking the next page button, the next page with different images will be there.

**Comment by Vedant003** [comment]
Hello, @MitAbhay ,can you please assign me the task?

**Comment by MitAbhay** [comment]
go ahead!

**Comment by MitAbhay** [comment]
Updates ??

**Comment by dylanullrich** [comment]
I can work on this one as well.

**Comment by dylanullrich** [comment]
@MitAbhay which branch would you like me to merge to for this PR?
