### ISSUE TITLE
Responsive footer by adding routes in it. 

### ISSUE THREAD

**Issue by chintan0513** [MitAbhay/hinna-henna#42]

**Comment by chintan0513** [comment]
Please assign me

**Comment by chintan0513** [comment]
I'm planning to move all footer .tsx file into React Footer component

**Comment by MitAbhay** [comment]
what routes you will add?

**Comment by chintan0513** [comment]
Social media

**Comment by MitAbhay** [comment]
No need for that right now as we don't have social media accounts for the website till.
