### ISSUE TITLE
Bug : Alert Library Implementation

### ISSUE THREAD

**Issue by MitAbhay** [MitAbhay/hinna-henna#48]
Every Time we are going to the home page, it's showing the welcome alert!
But it must only be one time.

**Comment by MitAbhay** [comment]
Note: Make the Pull Request in a specific branch of this feature : [feature/alert_library](https://github.com/MitAbhay/hinna-henna/tree/feature/alert-library)

**Comment by SubinDuresh** [comment]
Hi @MitAbhay, can I work on this issue? I can make it so that the popup will not show up again until the cache is cleared.
