### ISSUE TITLE
[FEATURE] Keep a unified color

### ISSUE THREAD

**Issue by Dun-sin** [MitAbhay/hinna-henna#5]
The project has too many shades of color, I think one is just fine, instead of different shades

1st shade:
![image](https://user-images.githubusercontent.com/78784850/193363134-94b37d92-dabf-4961-8db8-077dcfbc4000.png)

2nd shade:
![image](https://user-images.githubusercontent.com/78784850/193363183-141e8825-88f6-490d-ba83-334b6ef3fbdc.png)

3rd Shade:
![image](https://user-images.githubusercontent.com/78784850/193363225-b7ae9260-1701-4b19-aef5-31a34330c931.png)

4th Shade:
![image](https://user-images.githubusercontent.com/78784850/193363270-b605e26e-7f4e-4f35-8be6-42305fc6cf0f.png)

### Without a unified color:
![image](https://user-images.githubusercontent.com/78784850/193363723-24bd7880-237c-4c50-ae27-855f4cc5d500.png)

### With a unified color (using the 3rd shade):
![image](https://user-images.githubusercontent.com/78784850/193363583-8566583d-ecd2-462d-a332-b912c5cdd081.png)

**Comment by MitAbhay** [comment]
Yes, you are right @Dun-sin  , it looks better with one color, but I think there should be some better color combination rather than having only one color on the whole website. If you have some others ideas for colors for the website you can continue with this issue.

**Comment by Dun-sin** [comment]
> Yes, you are right @Dun-sin  , it looks better with one color, but I think there should be some better color combination rather than having only one color on the whole website. If you have some others ideas for colors for the website you can continue with this issue.

The Header and the footer can have the same color, the main highlighted sext can have a different color.

**Comment by MitAbhay** [comment]
ok, go ahead !! let's see the final result.
