### ISSUE TITLE
Services UI 

### ISSUE THREAD

**Issue by Shubham-Rasal** [MitAbhay/hinna-henna#9]
Can I work on the services ui ?

**Comment by MitAbhay** [comment]
Just first let me know in detail what improvements you can do.

**Comment by Shubham-Rasal** [comment]
### Improvements:
- [ ] Change the service card UI.
- [ ]  Make the services page responsive along with other pages.

**Comment by MitAbhay** [comment]
Can you make an animated card in this?? (But it should not cause the lagging in website)
